#!/bin/bash
#
# Issue Server Certificate
# 
# Usage: ./issue-server-cert.sh <cn> <san-dns> [<san-ip>]
# Example: ./issue-server-cert.sh hsm-service.local "hsm-service.local,localhost" "127.0.0.1"
#
# This script generates a server certificate with Subject Alternative Names (SAN)
# and updates the certificate inventory.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKI_DIR="$(dirname "$SCRIPT_DIR")"
CA_DIR="$PKI_DIR/ca"
SERVER_DIR="$PKI_DIR/server"
INVENTORY_FILE="$PKI_DIR/inventory.yaml"

# Check arguments
if [ $# -lt 2 ]; then
    echo -e "${RED}Error: Missing arguments${NC}"
    echo "Usage: $0 <cn> <san-dns> [<san-ip>]"
    echo ""
    echo "Arguments:"
    echo "  cn        Common Name (e.g., hsm-service.local)"
    echo "  san-dns   DNS names for SAN, comma-separated (e.g., 'hsm-service.local,localhost')"
    echo "  san-ip    IP addresses for SAN, comma-separated (optional, e.g., '127.0.0.1,10.0.0.5')"
    echo ""
    echo "Example:"
    echo "  $0 hsm-service.local 'hsm-service.local,localhost' '127.0.0.1'"
    exit 1
fi

CN="$1"
SAN_DNS="$2"
SAN_IP="${3:-}"

# Validate CA exists
if [ ! -f "$CA_DIR/ca.crt" ] || [ ! -f "$CA_DIR/ca.key" ]; then
    echo -e "${RED}Error: CA certificate or key not found in $CA_DIR${NC}"
    echo "Please ensure ca.crt and ca.key exist in $CA_DIR"
    exit 1
fi

# Create output directory if not exists
mkdir -p "$SERVER_DIR"

# File paths
KEY_FILE="$SERVER_DIR/${CN}.key"
CSR_FILE="$SERVER_DIR/${CN}.csr"
CERT_FILE="$SERVER_DIR/${CN}.crt"
EXT_FILE="$SERVER_DIR/${CN}.ext"

# Check if certificate already exists
if [ -f "$CERT_FILE" ]; then
    echo -e "${YELLOW}Warning: Certificate for $CN already exists${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

echo -e "${GREEN}Generating server certificate for: $CN${NC}"

# 1. Generate private key (RSA 4096)
echo "→ Generating RSA 4096 private key..."
openssl genrsa -out "$KEY_FILE" 4096 2>/dev/null
chmod 600 "$KEY_FILE"
echo "  ✓ Private key saved to $KEY_FILE"

# 2. Create CSR
echo "→ Creating Certificate Signing Request..."
SUBJECT="/C=RU/ST=Moscow/L=Moscow/O=Private/OU=Services/CN=${CN}"

openssl req -new \
    -key "$KEY_FILE" \
    -out "$CSR_FILE" \
    -subj "$SUBJECT" 2>/dev/null

echo "  ✓ CSR created with subject: $SUBJECT"

# 3. Create SAN extension file
echo "→ Creating SAN extension file..."
cat > "$EXT_FILE" <<EOF
subjectAltName = @alt_names
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth

[alt_names]
EOF

# Add DNS names
DNS_INDEX=1
IFS=',' read -ra DNS_ARRAY <<< "$SAN_DNS"
for dns in "${DNS_ARRAY[@]}"; do
    dns=$(echo "$dns" | xargs)  # trim whitespace
    if [ -n "$dns" ]; then
        echo "DNS.${DNS_INDEX} = ${dns}" >> "$EXT_FILE"
        ((DNS_INDEX++))
    fi
done

# Add IP addresses if provided
if [ -n "$SAN_IP" ]; then
    IP_INDEX=1
    IFS=',' read -ra IP_ARRAY <<< "$SAN_IP"
    for ip in "${IP_ARRAY[@]}"; do
        ip=$(echo "$ip" | xargs)  # trim whitespace
        if [ -n "$ip" ]; then
            echo "IP.${IP_INDEX} = ${ip}" >> "$EXT_FILE"
            ((IP_INDEX++))
        fi
    done
fi

echo "  ✓ SAN configuration created"

# 4. Sign certificate with CA
echo "→ Signing certificate with CA..."
openssl x509 -req \
    -in "$CSR_FILE" \
    -CA "$CA_DIR/ca.crt" \
    -CAkey "$CA_DIR/ca.key" \
    -CAcreateserial \
    -out "$CERT_FILE" \
    -days 365 \
    -sha256 \
    -extfile "$EXT_FILE" 2>/dev/null

echo "  ✓ Certificate signed and saved to $CERT_FILE"

# 5. Clean up temporary files
rm -f "$CSR_FILE" "$EXT_FILE"

# 6. Verify certificate
echo "→ Verifying certificate..."
if openssl verify -CAfile "$CA_DIR/ca.crt" "$CERT_FILE" >/dev/null 2>&1; then
    echo -e "  ${GREEN}✓ Certificate verification successful${NC}"
else
    echo -e "  ${RED}✗ Certificate verification failed${NC}"
    exit 1
fi

# 7. Extract certificate information
SERIAL=$(openssl x509 -in "$CERT_FILE" -noout -serial | cut -d'=' -f2)
NOT_BEFORE=$(openssl x509 -in "$CERT_FILE" -noout -startdate | cut -d'=' -f2)
NOT_AFTER=$(openssl x509 -in "$CERT_FILE" -noout -enddate | cut -d'=' -f2)
ISSUED_DATE=$(date -d "$NOT_BEFORE" +%Y-%m-%d 2>/dev/null || date -j -f "%b %d %T %Y %Z" "$NOT_BEFORE" +%Y-%m-%d)
EXPIRES_DATE=$(date -d "$NOT_AFTER" +%Y-%m-%d 2>/dev/null || date -j -f "%b %d %T %Y %Z" "$NOT_AFTER" +%Y-%m-%d)

# 8. Update inventory
echo "→ Updating inventory..."
if [ ! -f "$INVENTORY_FILE" ]; then
    cat > "$INVENTORY_FILE" <<EOF
# Certificate Inventory
# Auto-generated by PKI scripts
certificates:
  servers: []
  clients: []
EOF
fi

# Create temporary Python script for YAML manipulation
python3 - <<EOF
import yaml
import sys
from datetime import datetime

inventory_file = "$INVENTORY_FILE"

# Load existing inventory
try:
    with open(inventory_file, 'r') as f:
        inventory = yaml.safe_load(f) or {}
except:
    inventory = {}

if 'certificates' not in inventory:
    inventory['certificates'] = {}
if 'servers' not in inventory['certificates']:
    inventory['certificates']['servers'] = []

# Parse SAN
san_dns_list = [d.strip() for d in "$SAN_DNS".split(',') if d.strip()]
san_ip_list = [ip.strip() for ip in "$SAN_IP".split(',') if ip.strip()] if "$SAN_IP" else []

# Create new certificate entry
new_cert = {
    'cn': '$CN',
    'ou': 'Services',
    'issued': '$ISSUED_DATE',
    'expires': '$EXPIRES_DATE',
    'serial': '$SERIAL',
    'san_dns': san_dns_list,
    'san_ip': san_ip_list if san_ip_list else None,
    'file': 'server/$CN'
}

# Remove None values
new_cert = {k: v for k, v in new_cert.items() if v is not None}

# Remove existing entry with same CN if exists
inventory['certificates']['servers'] = [
    cert for cert in inventory['certificates']['servers'] 
    if cert.get('cn') != '$CN'
]

# Add new entry
inventory['certificates']['servers'].append(new_cert)

# Sort by CN
inventory['certificates']['servers'].sort(key=lambda x: x.get('cn', ''))

# Write back
with open(inventory_file, 'w') as f:
    yaml.dump(inventory, f, default_flow_style=False, sort_keys=False)

print("  ✓ Inventory updated")
EOF

# 9. Display certificate info
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Server Certificate Generated Successfully${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo "Common Name:    $CN"
echo "Subject:        $SUBJECT"
echo "Serial:         $SERIAL"
echo "Issued:         $ISSUED_DATE"
echo "Expires:        $EXPIRES_DATE"
echo "SAN DNS:        $SAN_DNS"
if [ -n "$SAN_IP" ]; then
    echo "SAN IP:         $SAN_IP"
fi
echo ""
echo "Files created:"
echo "  Certificate:  $CERT_FILE"
echo "  Private Key:  $KEY_FILE"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Copy certificate and key to your server"
echo "2. Configure your service to use these files"
echo "3. Ensure private key has restricted permissions (0600)"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
