#!/bin/bash
#
# Revoke Certificate
#
# Usage: ./revoke-cert.sh <cn> <reason>
# Example: ./revoke-cert.sh old-service compromised
#
# This script adds a certificate to the revoked list.
# Valid reasons: compromised, decommissioned, superseded, cessation

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKI_DIR="$(dirname "$SCRIPT_DIR")"
CLIENT_DIR="$PKI_DIR/client"
SERVER_DIR="$PKI_DIR/server"
REVOKED_FILE="$PKI_DIR/revoked.yaml"
INVENTORY_FILE="$PKI_DIR/inventory.yaml"

# Valid reasons
VALID_REASONS=("compromised" "decommissioned" "superseded" "cessation")

# Check arguments
if [ $# -lt 2 ]; then
    echo -e "${RED}Error: Missing arguments${NC}"
    echo "Usage: $0 <cn> <reason>"
    echo ""
    echo "Arguments:"
    echo "  cn      Common Name of certificate to revoke"
    echo "  reason  Reason for revocation"
    echo ""
    echo "Valid reasons:"
    echo "  compromised     - Private key or certificate compromised"
    echo "  decommissioned  - Service no longer in use"
    echo "  superseded      - Certificate replaced by new one"
    echo "  cessation       - Service ceased operation"
    echo ""
    echo "Example:"
    echo "  $0 old-trading-service compromised"
    exit 1
fi

CN="$1"
REASON="$2"

# Validate reason
if [[ ! " ${VALID_REASONS[@]} " =~ " ${REASON} " ]]; then
    echo -e "${RED}Error: Invalid reason: $REASON${NC}"
    echo "Valid reasons: ${VALID_REASONS[*]}"
    exit 1
fi

# Try to find certificate
CERT_FILE=""
if [ -f "$CLIENT_DIR/${CN}.crt" ]; then
    CERT_FILE="$CLIENT_DIR/${CN}.crt"
    CERT_TYPE="client"
elif [ -f "$SERVER_DIR/${CN}.crt" ]; then
    CERT_FILE="$SERVER_DIR/${CN}.crt"
    CERT_TYPE="server"
else
    echo -e "${YELLOW}Warning: Certificate file not found for CN=$CN${NC}"
    echo "Proceeding with revocation anyway (manual entry)..."
    CERT_TYPE="unknown"
fi

# Extract serial if certificate exists
if [ -n "$CERT_FILE" ] && [ -f "$CERT_FILE" ]; then
    SERIAL=$(openssl x509 -in "$CERT_FILE" -noout -serial | cut -d'=' -f2)
    echo "Found certificate:"
    echo "  CN:     $CN"
    echo "  Type:   $CERT_TYPE"
    echo "  Serial: $SERIAL"
    echo "  File:   $CERT_FILE"
else
    SERIAL="unknown"
    echo "Certificate not found in local PKI directories"
fi

echo ""
echo -e "${YELLOW}This will add the certificate to the revocation list.${NC}"
echo -e "${YELLOW}After restarting HSM service, this certificate will be rejected.${NC}"
echo ""
read -p "Continue? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

# Create revoked.yaml if not exists
if [ ! -f "$REVOKED_FILE" ]; then
    cat > "$REVOKED_FILE" <<EOF
# Certificate Revocation List
# Auto-generated by PKI scripts
revoked: []
EOF
fi

# Get current timestamp
REVOKED_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Update revoked.yaml
echo "→ Adding to revocation list..."
python3 - <<EOF
import yaml
from datetime import datetime

revoked_file = "$REVOKED_FILE"

# Load existing revoked list
try:
    with open(revoked_file, 'r') as f:
        data = yaml.safe_load(f) or {}
except:
    data = {}

if 'revoked' not in data:
    data['revoked'] = []

# Check if already revoked
for cert in data['revoked']:
    if cert.get('cn') == '$CN':
        print("  ${YELLOW}Warning: Certificate already in revoked list${NC}")
        exit(0)

# Add new revoked entry
new_entry = {
    'cn': '$CN',
    'serial': '$SERIAL',
    'revoked_date': '$REVOKED_DATE',
    'reason': '$REASON'
}

data['revoked'].append(new_entry)

# Sort by revoked_date (newest first)
data['revoked'].sort(key=lambda x: x.get('revoked_date', ''), reverse=True)

# Write back
with open(revoked_file, 'w') as f:
    yaml.dump(data, f, default_flow_style=False, sort_keys=False)

print("  ✓ Certificate added to revoked list")
EOF

# Display result
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Certificate Revoked${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo "CN:            $CN"
echo "Serial:        $SERIAL"
echo "Reason:        $REASON"
echo "Revoked Date:  $REVOKED_DATE"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Restart HSM service to reload revoked list:"
echo "   docker-compose restart hsm-service"
echo "   # OR send SIGHUP for hot reload (if implemented)"
echo ""
echo "2. The certificate will be immediately rejected"
echo ""
echo "3. Optionally, remove certificate files:"
if [ -n "$CERT_FILE" ] && [ -f "$CERT_FILE" ]; then
    echo "   rm $CERT_FILE"
    echo "   rm ${CERT_FILE%.crt}.key"
fi
echo ""
echo -e "${YELLOW}Revoked list location:${NC}"
echo "  $REVOKED_FILE"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
